# Generated by Django 4.2.4 on 2023-08-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image3', models.ImageField(null=True, upload_to='media/images')),
                ('product_name3', models.CharField(max_length=50)),
                ('product_price3', models.IntegerField(null=True)),
                ('product_rate3', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='panttrouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image2', models.ImageField(null=True, upload_to='media/images')),
                ('product_name2', models.CharField(max_length=50)),
                ('product_price2', models.IntegerField(null=True)),
                ('product_rate2', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='manwomen',
            old_name='product_name',
            new_name='product_name1',
        ),
        migrations.RemoveField(
            model_name='manwomen',
            name='product_price',
        ),
        migrations.AddField(
            model_name='manwomen',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AddField(
            model_name='manwomen',
            name='product_price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manwomen',
            name='product_rate1',
            field=models.IntegerField(null=True),
        ),
    ]
