# Generated by Django 4.2.4 on 2023-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_clothing_panttrouser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='product_image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='manwomen',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='panttrouser',
            name='product_image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
