# Generated by Django 4.2.4 on 2023-08-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_alter_clothing_product_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_imag4', models.ImageField(null=True, upload_to='images')),
                ('product_name4', models.CharField(max_length=50)),
                ('product_price4', models.IntegerField(null=True)),
                ('product_rate4', models.IntegerField(null=True)),
            ],
        ),
    ]
