# Generated by Django 4.2.4 on 2023-08-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='shopgrid',
        ),
    ]
