# Generated by Django 4.2.4 on 2023-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_shops1_shopsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops1detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name5', models.CharField(max_length=50)),
                ('product_price5', models.IntegerField(null=True)),
                ('product_rate5', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shops1img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_imag5', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='shops1',
        ),
    ]
