# Generated by Django 4.2.4 on 2023-08-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_shops1detail_shops1img_delete_shops1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_price_offer', models.IntegerField()),
                ('item_desc', models.TextField()),
                ('item_image', models.ImageField(null=True, upload_to='items')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='clothing',
        ),
        migrations.DeleteModel(
            name='manwomen',
        ),
        migrations.DeleteModel(
            name='panttrouser',
        ),
        migrations.DeleteModel(
            name='shopgrid',
        ),
        migrations.DeleteModel(
            name='shops1detail',
        ),
        migrations.DeleteModel(
            name='shops1img',
        ),
        migrations.DeleteModel(
            name='shopsg',
        ),
    ]
