# Generated by Django 4.2.4 on 2023-08-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_category_item_delete_clothing_delete_manwomen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='collection_id',
            new_name='Category_id',
        ),
    ]
