# Generated by Django 4.2.4 on 2023-08-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_rename_collection_id_item_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(null=True, upload_to='items')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.item')),
            ],
        ),
    ]
