# Generated by Django 4.2.4 on 2023-09-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_rename_item_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
